List<String> cdoBarangays = [
  'Agusan',
  'Baikingon',
  'Balubal',
  'Balulang',
  'Barangay 1',
  'Barangay 10',
  'Barangay 11',
  'Barangay 12',
  'Barangay 13',
  'Barangay 14',
  'Barangay 15',
  'Barangay 16',
  'Barangay 17',
  'Barangay 18',
  'Barangay 19',
  'Barangay 2',
  'Barangay 20',
  'Barangay 21',
  'Barangay 22',
  'Barangay 23',
  'Barangay 24',
  'Barangay 25',
  'Barangay 26',
  'Barangay 27',
  'Barangay 28',
  'Barangay 29',
  'Barangay 3',
  'Barangay 30',
  'Barangay 31',
  'Barangay 32',
  'Barangay 33',
  'Barangay 34',
  'Barangay 35',
  'Barangay 36',
  'Barangay 37',
  'Barangay 38',
  'Barangay 39',
  'Barangay 4',
  'Barangay 40',
  'Barangay 5',
  'Barangay 6',
  'Barangay 7',
  'Barangay 8',
  'Barangay 9',
  'Bayabas',
  'Bayanga',
  'Besigan',
  'Bonbon',
  'Bugo',
  'Bulua',
  'Camaman-an',
  'Canito-an',
  'Carmen',
  'Consolacion',
  'Cugman',
  'Dansolihon',
  'F. S. Catanico',
  'Gusa',
  'Indahag',
  'Iponan',
  'Kauswagan',
  'Lapasan',
  'Lumbia',
  'Macabalan',
  'Macasandig',
  'Mambuaya',
  'Nazareth',
  'Pagalungan',
  'Pagatpat',
  'Patag',
  'Pigsag-an',
  'Puerto',
  'Puntod',
  'San Simon',
  'Tablon',
  'Taglimao',
  'Tagpangi',
  'Tignapoloan',
  'Tuburan',
  'Tumpagon',
];
